{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failureReadingCredentials"},{"kind":"text","text":"("},{"kind":"externalParam","text":"reason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":2,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oauth2\/oauth2error\/failurereadingcredentials(reason:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/OAuth2\/documentation\/OAuth2\/OAuth2Error\/failureReadingCredentials(reason:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Error during serialization of credentials"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failureReadingCredentials"},{"kind":"text","text":"("},{"kind":"externalParam","text":"reason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"title":"OAuth2Error.failureReadingCredentials(reason:)","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"s:6OAuth20A5ErrorO25failureReadingCredentialsyACSS_tcACmF","modules":[{"name":"OAuth2"}]},"hierarchy":{"paths":[["doc:\/\/OAuth2\/documentation\/OAuth2","doc:\/\/OAuth2\/documentation\/OAuth2\/OAuth2Error"]]},"references":{"doc://OAuth2/documentation/OAuth2/OAuth2Error/failureReadingCredentials(reason:)":{"role":"symbol","title":"OAuth2Error.failureReadingCredentials(reason:)","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failureReadingCredentials"},{"kind":"text","text":"("},{"kind":"externalParam","text":"reason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Error during serialization of credentials"}],"identifier":"doc:\/\/OAuth2\/documentation\/OAuth2\/OAuth2Error\/failureReadingCredentials(reason:)","kind":"symbol","type":"topic","url":"\/documentation\/oauth2\/oauth2error\/failurereadingcredentials(reason:)"},"doc://OAuth2/documentation/OAuth2":{"role":"collection","title":"OAuth2","abstract":[{"type":"text","text":"An OAuth2 client to authenticate your app with a service provider."}],"identifier":"doc:\/\/OAuth2\/documentation\/OAuth2","kind":"symbol","type":"topic","url":"\/documentation\/oauth2"},"doc://OAuth2/documentation/OAuth2/OAuth2Error":{"role":"symbol","title":"OAuth2Error","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"OAuth2Error"}],"abstract":[{"type":"text","text":"Errors thrown by the OAuth2 client."}],"identifier":"doc:\/\/OAuth2\/documentation\/OAuth2\/OAuth2Error","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OAuth2Error"}],"url":"\/documentation\/oauth2\/oauth2error"}}}